name: wra_brunchyy
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pylint
  - pytest
  - pytest-cov
  - pip:
      - numpy
      - pandas
      - matplotlib
      - scipy
      - xarray
      - netCDF4
      - windrose
